import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { Providers } from '@/globalRedux/providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en" className="">
        <body
          className={`${inter.className} bg-[#FFDF8C] px-2  xl:px-10 h-full`}
        >
          <div className="bg-white max-w-[1400px] mx-auto my-2 xl:my-12  rounded-[10px] h-full">
            <Header />
            {children}
          </div>
        </body>
      </html>
    </Providers>
  )
}
